import type {MusicVideoProps} from './schema';
import {ACTIVE_TRACK_TOKEN} from './utils/audio-track';

export const defaultMusicVideoProps: MusicVideoProps = {
  template: 'neon-pulse',
  audioFile: ACTIVE_TRACK_TOKEN,
  coverFile: 'cover.svg',
  logoFile: 'logo.svg',
  title: 'Signal After Dark',
  artist: 'Northstar Audio',
  brandName: 'NORTHSTAR',
  eyebrow: 'OFFICIAL VISUAL // 001',
  website: 'northstar.audio',
  catalogLabel: 'NSR-001 / STEREO',
  callToAction: 'LISTEN •BECO INDUSTRIES',
  copyrightLine: '© 2026 NORTHSTAR AUDIO. ALL RIGHTS RESERVED.',
  backgroundColor: '#06070B',
  primaryColor: '#8C7BFF',
  secondaryColor: '#33D6FF',
  accentColor: '#FF5F8F',
  textColor: '#F7F8FF',
  mutedTextColor: '#A7ADC2',
  visualizerSamples: '64',
  intensity: 1.1,
  audioStartSeconds: 0,
  audioEndTrimSeconds: 0,
  outroSeconds: 2.5,
  outroPlacement: 'over-track-end',
  showCover: true,
  showVisualizer: true,
  showProgress: true,
  showTimecode: true,
  coverFit: 'cover',
};
